site_name: Tự học khá nhiều kĩ năng - Khu học mở
site_description: Tự học mọi sở thích thông qua hướng dẫn, lộ trình và các nguồn tài nguyên miễn phí trên Internet
site_author: duykhanh471
repo_url: https://github.com/daihocmo/ki-nang
repo_name: Gửi góp ý, phản hồi

nav:
  - 'Trang chủ': 'index.md'
  - 'Thủ công & Mỹ thuật':
    - 'Móc len (Crochet)': 'thu-cong-my-thuat/moc-len.md'
    - 'Thêu (Embroidery)': 'thu-cong-my-thuat/theu.md'
    - 'Đan len (Knitting)': 'thu-cong-my-thuat/dan-len.md'
    - 'May vá (Sewing)': 'thu-cong-my-thuat/may-va.md'
    - 'Origami': 'thu-cong-my-thuat/gap-giay-origami.md'
    - 'Vẽ minh họa': 'thu-cong-my-thuat/ve-minh-hoa.md'
    - 'Làm phim tài liệu': 'thu-cong-my-thuat/lam-phim-tai-lieu.md'
  - 'Trải nghiệm':
    - 'Leo núi': 'su-kien-giai-tri/leo-nui.md'
    - 'Câu cá': 'su-kien-giai-tri/cau-ca.md'
    - 'Cắm trại': 'su-kien-giai-tri/cam-trai.md'
    - 'Làm vườn': 'su-kien-giai-tri/lam-vuon.md'
  - 'Nhạc':
    - 'Beatboxing': 'am-nhac/beatboxing.md'
    - 'Nhảy Ballet': 'am-nhac/nhay-ballet.md'
    - 'Đàn Bass': 'am-nhac/dan-bass.md'
    - 'Bộ trống': 'am-nhac/bo-trong.md'
    - 'Sáo': 'am-nhac/dan-flute.md'
    - 'Guitar': 'am-nhac/dan-guitar.md'
    - 'Harmonica': 'am-nhac/dan-harmonica.md'
    - 'Piano': 'am-nhac/dan-piano.md'
    - 'Đàn Saxophone': 'am-nhac/dan-saxophone.md'
    - 'Đàn Trumpet': 'am-nhac/dan-trumpet.md'
    - 'Đàn Ukulele': 'am-nhac/dan-ukulele.md'
    - 'Đàn Violin': 'am-nhac/dan-violin.md'
  - 'Công nghệ & Truyền thông':
    - 'In 3D': 'cong-nghe-truyen-thong/in-3d.md'
    - 'Xây dựng PC': 'cong-nghe-truyen-thong/xay-dung-pc.md'
    - 'Podcasting': 'cong-nghe-truyen-thong/podcasting.md'
    - 'Sản xuất video': 'cong-nghe-truyen-thong/san-xuat-video.md'
    - 'Thiết kế âm thanh': 'cong-nghe-truyen-thong/thiet-ke-am-thanh.md'
  - 'Trò chơi':
    - 'Cờ đam': 'tro-choi-gaming/co-dam.md'
    - 'Cờ vua': 'tro-choi-gaming/co-vua.md'
    - 'Cờ vây': 'tro-choi-gaming/co-go.md'
    - 'Mạt chược': 'tro-choi-gaming/mat-chuoc.md'
    - 'Cờ tỉ phú': 'tro-choi-gaming/monopoly.md'
    - 'Ghép hình': 'tro-choi-gaming/ghep-hinh.md'
    - 'Rubik': 'tro-choi-gaming/rubik.md'
    - 'Shogi': 'tro-choi-gaming/co-shogi.md'
    - 'Sudoku': 'tro-choi-gaming/sudoku.md'
    - 'LitRPG': 'tro-choi-gaming/tro-choi-nhap-vai.md'
  - 'Thể thao & Thi đấu':
    - 'Cầu lông': 'the-thao-thi-dau/cau-long.md'
    - 'Bóng chày': 'the-thao-thi-dau/bong-chay.md'
    - 'Bowling': 'the-thao-thi-dau/bowling.md'
    - 'Đấm bốc': 'the-thao-thi-dau/dam-boc.md'
    - 'Croquet': 'the-thao-thi-dau/croquet.md'
    - 'Đấu kiếm': 'the-thao-thi-dau/dau-kiem.md'
    - 'Golf': 'the-thao-thi-dau/golf.md'
    - 'Thể dục dụng cụ': 'the-thao-thi-dau/the-duc-dung-cu.md'
    - 'Bóng ném': 'the-thao-thi-dau/bong-nem.md'
    - 'Pickleball': 'the-thao-thi-dau/pickleball.md'
    - 'Bóng rổ': 'the-thao-thi-dau/bong-ro.md'
    - 'Bóng đá': 'the-thao-thi-dau/bong-da.md'
    - 'Bóng chuyền': 'the-thao-thi-dau/bong-chuyen.md'
    - 'Quần vợt': 'the-thao-thi-dau/quan-vot.md'
  - 'Học tập & Nghiên cứu':
    - 'Thiên văn học': 'hoc-tap-nghien-cuu/thien-van-hoc.md'
    - 'Thực vật học': 'hoc-tap-nghien-cuu/thuc-vat-hoc.md'
    - 'Mật mã học': 'hoc-tap-nghien-cuu/mat-ma-hoc.md'

theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  icon:
    repo: fontawesome/brands/github
  language: vi
      
plugins:
  - search
  - open-in-new-tab
  
extra:
  generator: false