site_name: Nghiện tự học
site_description: Tự học mọi sở thích thông qua hướng dẫn, lộ trình và các nguồn tài nguyên miễn phí trên Internet
site_author: duykhanh471
repo_url: https://github.com/daihocmo/nghien-tu-hoc
repo_name: Gửi góp ý, phản hồi

nav:
  - 'Trang chủ': 'index.md'
  - 'Thủ công & Mỹ thuật':
    - 'Đan len (Crocheting)': 'thu-cong-my-thuat/dan-len.md'
    - 'Thêu (Embroidery)': 'thu-cong-my-thuat/theu.md'
    - 'Đan (Knitting)': 'thu-cong-my-thuat/dan.md'
    - 'May vá (Sewing)': 'thu-cong-my-thuat/may-va.md'
    - 'Ép hoa khô nghệ thuật': 'thu-cong-my-thuat/ep-hoa.md'
    - 'Thắt dây nghệ thuật': 'thu-cong-my-thuat/that-nut.md'
    - 'Origami': 'thu-cong-my-thuat/gap-giay-origami.md'
    - 'Nghệ thuật Pixel': 'thu-cong-my-thuat/nghe-thuat-pixel.md'
    - 'Vẽ minh họa': 'thu-cong-my-thuat/ve-minh-hoa.md'
    - 'Làm phim tài liệu': 'thu-cong-my-thuat/lam-phim-tai-lieu.md'
    - 'Sơn màu nước': 'thu-cong-my-thuat/son-mau-nuoc.md'
    - 'Tái chế sáng tạo': 'thu-cong-my-thuat/tai-che-sang-tao.md'
  - 'Trải nghiệm':
    - 'Biểu diễn kịch': 'su-kien-giai-tri/bieu-dien-kich.md'
    - 'Trượt patin': 'su-kien-giai-tri/truot-patin.md'
    - 'Trượt ván': 'su-kien-giai-tri/truot-van.md'
    - 'Đua xe đạp địa hình': 'su-kien-giai-tri/dua-xe-dap-dia-hinh.md'
    - 'Leo núi': 'su-kien-giai-tri/leo-nui.md'
    - 'Câu cá': 'su-kien-giai-tri/cau-ca.md'
    - 'Lặn': 'su-kien-giai-tri/lan-tu-do.md'
    - 'Bay lượn': 'su-kien-giai-tri/bay-luon.md'
    - 'Đi bộ đường dài': 'su-kien-giai-tri/di-bo-duong-dai.md'
    - 'Cắm trại': 'su-kien-giai-tri/cam-trai.md'
    - 'Leo núi': 'su-kien-giai-tri/leo-nui.md'
    - 'Đạp xe': 'su-kien-giai-tri/dap-xe.md'
    - 'Chèo thuyền': 'su-kien-giai-tri/cheo-thuyen.md'
    - 'Trồng cây ăn quả': 'su-kien-giai-tri/trong-cay-an-qua.md'
    - 'Làm vườn': 'su-kien-giai-tri/lam-vuon.md'
    - 'Thủy canh': 'su-kien-giai-tri/thuy-canh.md'
    - 'Thám hiểm hang động': 'su-kien-giai-tri/tham-hiem-hang-dong.md'
    - 'Lướt sóng': 'su-kien-giai-tri/luot-song.md'
    - 'Du lịch tối giản': 'su-kien-giai-tri/du-lich-toi-gian.md'
    - 'Du lịch đường bộ': 'su-kien-giai-tri/du-lich-duong-bo.md'
  - 'Ăn uống':
    - 'Nướng thịt': 'am-thuc-do-uong/nuong-thit.md'
    - 'Kem': 'am-thuc-do-uong/kem.md'
    - 'Nấu ăn chay': 'am-thuc-do-uong/nau-an-chay.md'
    - 'Trà': 'am-thuc-do-uong/tra.md'
    - 'Nấu ăn ngoài trời': 'am-thuc-do-uong/nau-an-ngoai-troi.md'
  - 'Nhạc':
    - 'Beatboxing': 'am-nhac/beatboxing.md'
    - 'Nhảy Ballet': 'am-nhac/nhay-ballet.md'
    - 'Đàn Bass': 'am-nhac/dan-bass.md'
    - 'Bộ trống': 'am-nhac/bo-trong.md'
    - 'Sáo': 'am-nhac/dan-flute.md'
    - 'Guitar': 'am-nhac/dan-guitar.md'
    - 'Harmonica': 'am-nhac/dan-harmonica.md'
    - 'Piano': 'am-nhac/dan-piano.md'
    - 'Đàn Saxophone': 'am-nhac/dan-saxophone.md'
    - 'Đàn Trumpet': 'am-nhac/dan-trumpet.md'
    - 'Đàn Ukulele': 'am-nhac/dan-ukulele.md'
    - 'Đàn Violin': 'am-nhac/dan-violin.md'
    - 'Sáng tác nhạc': 'am-nhac/sang-tac-nhac.md'
  - 'Công nghệ & Truyền thông':
    - 'In 3D': 'cong-nghe-truyen-thong/in-3d.md'
    - 'Thực tế tăng cường': 'cong-nghe-truyen-thong/thuc-te-tang-cuong.md'
    - 'Sản xuất video bằng drone': 'cong-nghe-truyen-thong/san-xuat-video-bang-drone.md'
    - 'Xây dựng PC': 'cong-nghe-truyen-thong/xay-dung-pc.md'
    - 'Podcasting': 'cong-nghe-truyen-thong/podcasting.md'
    - 'Biên tập video': 'cong-nghe-truyen-thong/bien-tap-video.md'
    - 'Sản xuất video': 'cong-nghe-truyen-thong/san-xuat-video.md'
    - 'Thiết kế âm thanh': 'cong-nghe-truyen-thong/thiet-ke-am-thanh.md'
    - 'Hiệu ứng đặc biệt': 'cong-nghe-truyen-thong/hieu-ung-dac-biet.md'
    - 'Hiệu ứng hình ảnh': 'cong-nghe-truyen-thong/hieu-ung-hinh-anh.md'
    - 'Thực tế ảo': 'cong-nghe-truyen-thong/thuc-te-ao.md'
  - 'Trò chơi':
    - 'Cờ đam': 'tro-choi-gaming/co-dam.md'
    - 'Cờ vua': 'tro-choi-gaming/co-vua.md'
    - 'Cờ vây': 'tro-choi-gaming/co-go.md'
    - 'Mạt chược': 'tro-choi-gaming/mat-chuoc.md'
    - 'Cờ tỉ phú': 'tro-choi-gaming/monopoly.md'
    - 'Ghép hình': 'tro-choi-gaming/ghep-hinh.md'
    - 'Rubik': 'tro-choi-gaming/rubik.md'
    - 'Dungeons and Dragons': 'tro-choi-gaming/dungeons-and-dragons.md'
    - 'Scrabble': 'tro-choi-gaming/scrabble.md'
    - 'Shogi': 'tro-choi-gaming/co-shogi.md'
    - 'Sudoku': 'tro-choi-gaming/sudoku.md'
    - 'LitRPG': 'tro-choi-gaming/tro-choi-nhap-vai.md'
    - 'Trò chơi chiến thuật': 'tro-choi-gaming/tro-choi-chien-thuat.md'
  - 'Dịch vụ':
    - 'Hoạt động vì động vật': 'dich-vu-cong-viec-nghia-vu/hoat-dong-vi-dong-vat.md'
    - 'Trị liệu nghiệp dư': 'dich-vu-cong-viec-nghia-vu/tri-lieu-nghiep-du.md'
    - 'Trị liệu mối quan hệ': 'dich-vu-cong-viec-nghia-vu/tri-lieu-moi-quan-he.md'
    - 'Pha chế': 'dich-vu-cong-viec-nghia-vu/pha-che.md'
    - 'Lập kế hoạch sự kiện': 'dich-vu-cong-viec-nghia-vu/lap-ke-hoach-su-kien.md'
    - 'Trang trí ngày lễ': 'dich-vu-cong-viec-nghia-vu/trang-tri-ngay-le.md'
    - 'Thợ cơ khí': 'dich-vu-cong-viec-nghia-vu/tho-co-khi.md'
    - 'Lập kế hoạch du lịch': 'dich-vu-cong-viec-nghia-vu/lap-ke-hoach-du-lich.md'
    - 'Trông trẻ': 'dich-vu-cong-viec-nghia-vu/trong-tre.md'
    - 'Dắt chó đi dạo': 'dich-vu-cong-viec-nghia-vu/dat-cho-di-dao.md'
    - 'Trông thú cưng': 'dich-vu-cong-viec-nghia-vu/trong-thu-cung.md'
    - 'Gia sư': 'dich-vu-cong-viec-nghia-vu/gia-su.md'
    - 'Chăm sóc người già': 'dich-vu-cong-viec-nghia-vu/cham-soc-nguoi-gia.md'
    - 'Cắt tóc': 'dich-vu-cong-viec-nghia-vu/cat-toc.md'
  - 'Thể thao & Thi đấu':
    - 'Bắn cung': 'the-thao-thi-dau/ban-cung.md'
    - 'Cầu lông': 'the-thao-thi-dau/cau-long.md'
    - 'Bóng chày': 'the-thao-thi-dau/bong-chay.md'
    - 'Bowling': 'the-thao-thi-dau/bowling.md'
    - 'Đấm bốc': 'the-thao-thi-dau/dam-boc.md'
    - 'Croquet': 'the-thao-thi-dau/croquet.md'
    - 'Đấu kiếm': 'the-thao-thi-dau/dau-kiem.md'
    - 'Golf': 'the-thao-thi-dau/golf.md'
    - 'Thể dục dụng cụ': 'the-thao-thi-dau/the-duc-dung-cu.md'
    - 'Bóng ném': 'the-thao-thi-dau/bong-nem.md'
    - 'Pickleball': 'the-thao-thi-dau/pickleball.md'
    - 'Bóng rổ': 'the-thao-thi-dau/bong-ro.md'
    - 'Bóng né': 'the-thao-thi-dau/bong-ne.md'
    - 'Bóng đá': 'the-thao-thi-dau/bong-da.md'
    - 'Bóng chuyền': 'the-thao-thi-dau/bong-chuyen.md'
    - 'Quần vợt': 'the-thao-thi-dau/quan-vot.md'
  - 'Học tập & Nghiên cứu':
    - 'Khảo cổ học': 'hoc-tap-nghien-cuu/khao-co-hoc.md'
    - 'Thiên văn học': 'hoc-tap-nghien-cuu/thien-van-hoc.md'
    - 'Sinh học động vật': 'hoc-tap-nghien-cuu/sinh-hoc-dong-vat.md'
    - 'Thực vật học': 'hoc-tap-nghien-cuu/thuc-vat-hoc.md'
    - 'Mật mã học': 'hoc-tap-nghien-cuu/mat-ma-hoc.md'
    - 'Gia phả học': 'hoc-tap-nghien-cuu/gia-pha-hoc.md'
    - 'Địa chất học': 'hoc-tap-nghien-cuu/dia-chat-hoc.md'
    - 'Luật học': 'hoc-tap-nghien-cuu/luat-hoc.md'
    - 'Sinh học biển': 'hoc-tap-nghien-cuu/sinh-hoc-bien.md'
    - 'Khí tượng học': 'hoc-tap-nghien-cuu/khi-tuong-hoc.md'
    - 'Vi sinh vật học': 'hoc-tap-nghien-cuu/vi-sinh-vat-hoc.md'
    - 'Khoa học thần kinh': 'hoc-tap-nghien-cuu/khoa-hoc-than-kinh.md'
    - 'Cổ sinh vật học': 'hoc-tap-nghien-cuu/co-sinh-vat-hoc.md'

theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  icon:
    repo: fontawesome/brands/github
  language: vi
      
plugins:
  - search
  - open-in-new-tab
  
extra:
  generator: false